baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'HU Fusion'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 4
  [[menu.main]]
    name = "Group"
    url = "/group/"
    weight = 5